server:
  port: 2022
  error:
    include-message: always
    include-binding-errors: always
# Spring Boot configuration
spring:
  application:
    name: simple-relational-database
    version: @project.version@
  liquibase.change-log: "classpath:/db/changelog/db.changelog-master.xml"

  tomcat:
    uri-encoding: UTF-8
  messages:
    basename: i18n.messages
    encoding: UTF-8

  # Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpledb?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

